// Curated catalogue of the Paris mathematical event ecosystem.
// Everything here was read on the official pages during the research phase (September 2026).
// Fields not stated by a source are null — recurrence, weekday, time and room are NEVER inferred.

import type { InstitutionData } from "../src/shared/types";
import type { RawSeries, SourceDef } from "./models";

export const ARXIV_CATEGORIES = ["math.AT", "math.GT", "math.AG", "math.CT", "math.KT", "math.QA", "math.CO", "math.DS"];

const I = (id: string, name: string, short_name: string, kind: string, parent: string, url: string, notes = ""): InstitutionData =>
  ({ id, name, short_name, kind, parent, url, notes });

export const INSTITUTIONS: InstitutionData[] = [
  I("imj-prg", "Institut de Mathématiques de Jussieu–Paris Rive Gauche", "IMJ-PRG", "laboratory", "Sorbonne Université, Université Paris Cité, CNRS",
    "https://www.imj-prg.fr", "Two sites: Jussieu (Sorbonne Université) and Sophie Germain (Université Paris Cité)."),
  I("ens-dma", "Département de mathématiques et applications, ENS", "ENS DMA", "department", "ENS-PSL, CNRS", "https://www.math.ens.psl.eu",
    "Old domain math.ens.psl.fr fails TLS; the live site is math.ens.psl.eu."),
  I("ihp", "Institut Henri Poincaré", "IHP", "institute", "Sorbonne Université, CNRS", "https://www.ihp.fr",
    "Hosts many inter-university Paris seminars, the Séminaire Bourbaki and thematic trimesters (Centre Émile Borel)."),
  I("ihes", "Institut des Hautes Études Scientifiques", "IHES", "institute", "", "https://www.ihes.fr", "Bures-sur-Yvette (RER B)."),
  I("laga", "Laboratoire Analyse, Géométrie et Applications", "LAGA", "laboratory", "Université Sorbonne Paris Nord, Université Paris 8, CNRS",
    "https://www.math.univ-paris13.fr", "Main site: Institut Galilée, Villetaneuse."),
  I("irif", "Institut de Recherche en Informatique Fondamentale", "IRIF", "laboratory", "Université Paris Cité, CNRS", "https://www.irif.fr",
    "Theoretical CS lab with category theory / homotopy type theory working groups (Sophie Germain building)."),
  I("lmo", "Laboratoire de Mathématiques d'Orsay (Institut de Mathématique d'Orsay)", "IMO / LMO", "laboratory", "Université Paris-Saclay, CNRS",
    "https://www.imo.universite-paris-saclay.fr"),
  I("cmls", "Centre de Mathématiques Laurent Schwartz", "CMLS", "laboratory", "École polytechnique (IP Paris), CNRS", "https://cmls.ip-paris.fr"),
  I("agm", "Analyse, Géométrie et Modélisation", "AGM (Cergy)", "laboratory", "CY Cergy Paris Université, CNRS", "https://cyagm.cyu.fr",
    "Site Saint-Martin, Pontoise."),
  I("ceremade", "CEREMADE", "CEREMADE", "laboratory", "Université Paris Dauphine-PSL, CNRS", "https://www.ceremade.dauphine.fr"),
  I("lpsm", "Laboratoire de Probabilités, Statistique et Modélisation", "LPSM", "laboratory", "Sorbonne Université, Université Paris Cité, CNRS",
    "https://www.lpsm.paris"),
  I("ljll", "Laboratoire Jacques-Louis Lions", "LJLL", "laboratory", "Sorbonne Université, Université Paris Cité, CNRS", "https://www.ljll.fr"),
  I("lama", "Laboratoire d'Analyse et de Mathématiques Appliquées", "LAMA", "laboratory", "Université Paris-Est Créteil, Université Gustave Eiffel, CNRS",
    "https://lama.u-pem.fr"),
  I("gustave-eiffel", "Université Gustave Eiffel", "U. Gustave Eiffel", "university", "", "https://www.univ-gustave-eiffel.fr"),
  I("upec", "Université Paris-Est Créteil", "UPEC", "university", "", "https://www.u-pec.fr"),
  I("cermics", "CERMICS", "CERMICS", "laboratory", "École nationale des ponts et chaussées", "https://cermics.enpc.fr"),
  I("map5", "MAP5", "MAP5", "laboratory", "Université Paris Cité, CNRS", "https://map5.mi.parisdescartes.fr"),
  I("lmv", "Laboratoire de Mathématiques de Versailles", "LMV", "laboratory", "UVSQ, CNRS", "https://lmv.math.cnrs.fr"),
  I("lamme", "Laboratoire de Mathématiques et Modélisation d'Évry", "LaMME", "laboratory", "Université d'Évry, CNRS", "http://www.math-evry.cnrs.fr"),
  I("modalx", "Modal'X", "Modal'X", "laboratory", "Université Paris Nanterre", "https://modalx.parisnanterre.fr"),
  I("cnam", "Conservatoire National des Arts et Métiers", "Cnam", "school", "", "https://www.cnam.fr"),
  I("telecom", "Télécom Paris", "Télécom Paris", "school", "IP Paris", "https://www.telecom-paris.fr"),
  I("polytechnique", "École polytechnique", "Polytechnique", "school", "IP Paris", "https://www.polytechnique.edu"),
  I("paris-saclay", "Université Paris-Saclay", "Paris-Saclay", "university", "", "https://www.universite-paris-saclay.fr"),
  I("sorbonne-universite", "Sorbonne Université", "Sorbonne U.", "university", "", "https://www.sorbonne-universite.fr"),
  I("fsmp", "Fondation Sciences Mathématiques de Paris", "FSMP", "foundation", "", "https://www.sciencesmaths-paris.fr"),
];

// Indico CNRS "Région Parisienne" (category 6) sub-categories, verified on https://indico.math.cnrs.fr/category/6/
export const INDICO_PARIS_CATEGORIES: [number, string, string][] = [
  [237, "imj-prg", "Institut de Mathématiques de Jussieu-Paris Rive Gauche, IMJ-PRG"],
  [107, "ihp", "Institut Henri Poincaré"],
  [57, "ihes", "I.H.E.S"],
  [227, "polytechnique", "Ecole polytechnique"],
  [331, "agm", "CY Cergy Paris Université"],
  [548, "gustave-eiffel", "Université Gustave Eiffel"],
  [554, "upec", "Université Paris-Est Créteil"],
  [250, "sorbonne-universite", "Université Paris 6 Pierre et Marie Curie"],
  [101, "ceremade", "Université Paris Dauphine (9) - CEREMADE"],
  [110, "map5", "Université Paris Descartes (5) - MAP5"],
  [222, "laga", "Université Paris Nord (13) - LAGA"],
  [173, "paris-saclay", "Université Paris-Saclay"],
  [689, "modalx", "Université Paris Nanterre - Modal'X"],
  [735, "lmv", "Laboratoire de mathématiques de Versailles (LMV - UVSQ)"],
  [549, "lama", "Laboratoire d'Analyse et de Mathématiques Appliquées (UPEC/UGE)"],
  [773, "cermics", "CERMICS"],
  [22, "cnam", "Conservatoire National des Arts et Métiers"],
  [295, "telecom", "Télécom Paris Tech"],
  [763, "lamme", "Université d'Evry Val d'Essonne - LaMME"],
];

// IRIF seminar codes (https://www.irif.fr/seminaires/index) with mathematical content.
export const IRIF_SEMINARS: [string, string, string[], string][] = [
  ["cat", "Catégories supérieures, polygraphes et homotopie", ["higher-categories", "homotopy-theory", "category-theory"], "working_group"],
  ["hott", "La théorie des types et la théorie de l'homotopie", ["homotopy-theory", "logic", "category-theory"], "working_group"],
  ["topos", "Topos pour la réalisabilité", ["category-theory", "logic"], "working_group"],
  ["picube", "Séminaire Formath (Formalized Mathematics)", ["logic"], "seminar"],
  ["combi", "Combinatoire énumérative et analytique", ["combinatorics"], "seminar"],
  ["laag", "Logique, automates, algèbre et jeux", ["logic", "algebra"], "seminar"],
  ["semantique", "Sémantique", ["logic", "category-theory"], "seminar"],
  ["types", "Théorie des types et son implémentation", ["logic"], "working_group"],
  ["gel", "Graphes et Logique", ["logic", "combinatorics"], "working_group"],
  ["adg", "Théorie des graphes", ["combinatorics"], "seminar"],
  ["irif", "IRIF Distinguished Talks Series", ["general"], "colloquium"],
];

// LAGA team seminar pages: [code, series name, team, organisers (as printed), page, topics]
export const LAGA_SEMINARS: [string, string, string, string, string, string[]][] = [
  ["sta", "Séminaire de l'équipe Topologie Algébrique", "Topologie Algébrique", "Charles De Clercq, Bruno Vallette, Geoffroy Horel",
    "https://www.math.univ-paris13.fr/accueil/equipes/ta/seminaire-de-lequipe-ta/", ["algebraic-topology", "homotopy-theory", "topology"]],
  ["sga", "Séminaire de l'équipe Arithmétique et Géométrie Algébrique", "Arithmétique et Géométrie Algébrique", "F. Scavia, M. Tamiozzo",
    "https://www.math.univ-paris13.fr/accueil/equipes/aga/seminaire-de-lequipe-aga/", ["number-theory", "algebraic-geometry"]],
  ["spi", "Séminaire de l'équipe AGC3", "AGC3", "Wolfgang Schmid, Martino Borello",
    "https://www.math.univ-paris13.fr/accueil/equipes/agc3/seminaire-de-lequipe-agc3/", []],
  ["gtenl", "Séminaire de l'équipe Physique Mathématique & EDP", "Physique Mathématique & Équations aux Dérivées Partielles", "P. Millet, C. Valcu",
    "https://www.math.univ-paris13.fr/accueil/equipes/pm/seminaire-de-lequipe-pm/", ["mathematical-physics", "pde"]],
  ["sps", "Séminaire de l'équipe Probabilités et Statistique", "Probabilités et Statistique", "Henri Elad-Altman, Laurent Tournier",
    "https://www.math.univ-paris13.fr/accueil/equipes/ps/seminaire-de-lequipe-ps/", ["probability"]],
  ["stesd", "Séminaire de l'équipe Systèmes Dynamiques", "Systèmes Dynamiques", "Timothée Bénard, Charles Fougeron, Mingkun Liu",
    "https://www.math.univ-paris13.fr/accueil/equipes/sd/seminaire-de-lequipe-sd/", ["dynamical-systems"]],
  ["saa", "Séminaire de l'équipe Modélisation et Calcul Scientifique", "Modélisation et Calcul Scientifique", "M. Darbas, E. Audusse",
    "https://www.math.univ-paris13.fr/accueil/equipes/mcs/seminaire-de-lequipe-mcs/", ["applied"]],
  ["mb", "Séminaire de l'équipe Mathématiques pour la Biologie et les Images", "Mathématiques pour la Biologie et les Images",
    "Sarah Kaakai, Frank Alvarez, Madeleine Kubasch", "https://www.math.univ-paris13.fr/accueil/equipes/mbi/seminaire-de-lequipe-mbi/", ["applied"]],
];

const S = (s: Partial<SourceDef> & Pick<SourceDef, "id" | "name" | "institution_id" | "url" | "extraction_method">): SourceDef => ({
  adapter: null, params: {}, calendar_url: null, reliability: "very_high", update_frequency: "every 6 h", notes: "", ...s,
});

export const SOURCES: SourceDef[] = [
  S({ id: "imj-gestion", name: "IMJ-PRG — Gestion des événements (all seminars & working groups)", institution_id: "imj-prg", adapter: "imj",
    url: "https://www.imj-prg.fr/gestion/evenement", calendar_url: "https://www.imj-prg.fr/gestion/evenement/ical/<seance>.ics",
    extraction_method: "HTML scraping of series pages + per-talk pages (per-talk ICS available)",
    notes: "Central database behind every IMJ-PRG seminar. ~105 series (many historical). Future sessions, including announced 'TBA' slots, are listed on each series page." }),
  S({ id: "gcal-imj-geomtop", name: "Google Calendar — Séminaire Géométrie et Topologie (IMJ-PRG)", institution_id: "imj-prg", adapter: "ical",
    params: { url: "https://calendar.google.com/calendar/ical/t8352hs3ft8e2ngob31rpijlts%40group.calendar.google.com/public/basic.ics",
      series_id: "imj-77", summary_is_speaker: true, location_hint: "jussieu", official_url: "https://www.imj-prg.fr/gestion/evenement/affEvenement/77" },
    url: "https://www.imj-prg.fr/gestion/evenement/affEvenement/77",
    calendar_url: "https://calendar.google.com/calendar/ical/t8352hs3ft8e2ngob31rpijlts%40group.calendar.google.com/public/basic.ics",
    extraction_method: "Public Google Calendar (ICS)",
    notes: "Linked from the seminar page. Entries usually contain only the speaker's name — used to confirm IMJ entries, never to provide titles. Last entry in March 2024." }),
  S({ id: "ens-dma", name: "ENS DMA — events calendar (all seminars)", institution_id: "ens-dma", adapter: "ens",
    url: "https://www.math.ens.psl.eu/la-recherche/seminaires/", calendar_url: "https://www.math.ens.psl.eu/evenements/?ical=1",
    extraction_method: "JSON REST API (WordPress The Events Calendar: /wp-json/tribe/events/v1/events)",
    notes: "Structured categories = seminar series. Several ENS series listed as 'archives' publish nothing now." }),
  S({ id: "ihp-agenda", name: "IHP — Agenda", institution_id: "ihp", adapter: "ihp", params: { pages: 6 }, url: "https://www.ihp.fr/fr/agenda",
    extraction_method: "HTML scraping of paginated agenda (/fr/agenda?page=N)", update_frequency: "every 12 h",
    notes: "agenda.xml returns HTTP 500. Also lists events of IHP partners held outside Paris (e.g. Cargèse) — flagged as outside the region. Most IHP talks are also on Indico (deduplicated)." }),
  S({ id: "ihp-recurrent", name: "IHP — Recurring seminars & working groups (catalogue page)", institution_id: "ihp", adapter: "ihp_recurrent",
    url: "https://www.ihp.fr/fr/seminaires-recurrents-et-groupes-de-travail", reliability: "high", update_frequency: "weekly",
    extraction_method: "HTML scraping (series discovery: name, frequency, weekday, link)",
    notes: "Discovers inter-university series hosted at IHP; talks come from their own sources." }),
  S({ id: "ihes-events", name: "IHES — Events (seminars, cours, conferences)", institution_id: "ihes", adapter: "ihes",
    url: "https://www.ihes.fr/en/events/", calendar_url: "https://indico.math.cnrs.fr/category/57/", update_frequency: "every 12 h",
    extraction_method: "HTML scraping (event tables link to Indico)", notes: "Every row links to its Indico event, which makes deduplication exact." }),
  S({ id: "imo-orsay", name: "Institut de Mathématique d'Orsay — Séminaires et événements", institution_id: "lmo", adapter: "imo", params: { detail_days: 21 },
    url: "https://www.imo.universite-paris-saclay.fr/fr/activites/les-evenements-de-limo/", update_frequency: "every 12 h",
    extraction_method: "HTML scraping (list cards + event detail pages)", notes: "Orsay plateau: count ~1 h from central Paris." }),
  S({ id: "cmls-geometrie", name: "CMLS (Polytechnique) — Séminaire de géométrie", institution_id: "cmls", adapter: "probe", params: { expect: "manual" },
    url: "https://cmls.ip-paris.fr/recherche/geometrie-et-dynamique/seminaire-de-geometrie", reliability: "high", update_frequency: "probe daily",
    extraction_method: "manual (irregular free-text page)",
    notes: "Sessions are written as free prose with inconsistent date headers (e.g. a header dated 7 July announcing a session on 24 June); automatic extraction would risk wrong dates." }),
  S({ id: "agm-seminaires", name: "AGM (Cergy) — Séminaires", institution_id: "agm", adapter: "probe",
    params: { expect: "fresh", urls: ["https://cyagm.cyu.fr/seminaire-geometrie-et-systemes-dynamiques-1", "https://cyagm.cyu.fr/seminaires-agm"] },
    url: "https://cyagm.cyu.fr/seminaires-agm", reliability: "high", update_frequency: "probe daily", extraction_method: "HTML (probe only)",
    notes: "In Sept. 2026 the seminar pages only showed 2024 sessions; the RSS export is empty. Cergy events published on Indico (category 331) are still ingested." }),
  S({ id: "lpsm-seminaires", name: "LPSM — Séminaires", institution_id: "lpsm", adapter: "probe", params: { expect: "fresh" },
    url: "https://www.lpsm.paris/seminaires/", reliability: "high", update_frequency: "probe daily", extraction_method: "blocked (anti-bot challenge)",
    notes: "Protected by an 'Anubis' proof-of-work bot wall; would need a headless browser." }),
  S({ id: "ljll-seminaires", name: "LJLL — Séminaires", institution_id: "ljll", adapter: "probe", params: { expect: "fresh" },
    url: "https://www.ljll.fr/seminaires/", reliability: "high", update_frequency: "probe daily", extraction_method: "blocked (anti-bot challenge)",
    notes: "Same bot wall as LPSM." }),
  S({ id: "ceremade-seminaires", name: "CEREMADE (Dauphine) — Séminaires", institution_id: "ceremade", adapter: "probe", params: { expect: "manual" },
    url: "https://www.ceremade.dauphine.fr/fr/seminaires.html", reliability: "high", update_frequency: "probe daily",
    extraction_method: "manual (TYPO3 pages; 'cette semaine au labo' empty at check time)", notes: "Dauphine events on Indico (category 101) are ingested." }),
  S({ id: "fsmp-agenda", name: "FSMP — Agenda & actualités", institution_id: "fsmp", url: "https://www.sciencesmaths-paris.fr/fr/actualites",
    extraction_method: "catalogued only", reliability: "high", update_frequency: "—", notes: "Mostly programmes, calls and outreach (e.g. Horizon Maths)." }),
  S({ id: "list-sem-top", name: "Mailing list sem-top.paris (Paris topology seminars)", institution_id: "imj-prg",
    url: "https://listes.services.cnrs.fr/wws/info/sem-top.paris", extraction_method: "mailing list (subscribe manually; archive not public)",
    reliability: "medium_high", update_frequency: "—",
    notes: "Created for the IMJ-PRG topology seminar and 'open to all topology seminars of the Paris region'. Announcements for topology afternoons/special days circulate there." }),
  S({ id: "list-gdt-top", name: "Mailing list gdt.top.imj-prg (Groupe de travail — Topologie Algébrique)", institution_id: "imj-prg",
    url: "https://listes.services.cnrs.fr/wws/info/gdt.top.imj-prg", extraction_method: "mailing list (subscribe manually)", reliability: "medium_high",
    update_frequency: "—" }),
  ...INDICO_PARIS_CATEGORIES.map(([cid, inst, label]) => S({
    id: `indico-${cid}`, name: `Indico CNRS — ${label}`, institution_id: inst, adapter: "indico", params: { category: cid },
    url: `https://indico.math.cnrs.fr/category/${cid}/`, calendar_url: `https://indico.math.cnrs.fr/category/${cid}/events.ics`,
    extraction_method: "Indico HTTP export API (JSON) incl. sub-categories", notes: "Sub-category names are used as series names.",
  })),
  ...IRIF_SEMINARS.map(([code, name]) => S({
    id: `irif-${code}`, name: `IRIF — ${name}`, institution_id: "irif", adapter: "ical",
    params: { url: `https://www.irif.fr/_media/ical/${code}.ics`, series_id: `irif-${code}`, location_hint: "sophie-germain", speaker_after_dash: true,
      official_url: `https://www.irif.fr/seminaires/${code}/index` },
    url: `https://www.irif.fr/seminaires/${code}/index`, calendar_url: `https://www.irif.fr/_media/ical/${code}.ics`, extraction_method: "ICS",
    update_frequency: "every 12 h",
  })),
  ...LAGA_SEMINARS.map(([code, name, , , page]) => S({
    id: `laga-${code}`, name: `LAGA — ${name}`, institution_id: "laga", adapter: "laga", params: { page, series_id: `laga-${code}` },
    url: page, calendar_url: `https://www.math.univ-paris13.fr/applications/seminaires/ical/${code}.ics`, update_frequency: "every 12 h",
    extraction_method: "HTML scraping of the seminar database listing (GET upcoming + POST current year)",
    notes: "The ICS and RSS links on the page exist but have not been regenerated since June 2023 — do not subscribe to them. Speaker homepages are linked by the source.",
  })),
];

export const SERIES: RawSeries[] = [
  { id: "imj-77", name: "Séminaire Géométrie et Topologie", institution_id: "imj-prg", department: "Équipes Analyse Algébrique ; Analyse Complexe et Géométrie",
    source_id: "imj-gestion", organizers: "S. André, R. Avdek, F. Ben Aribi, H. Eynard-Bontemps, P.-A. Guihéneuf, J. Marché, M. Mazzucchelli, B. Petri",
    official_url: "https://www.imj-prg.fr/gestion/evenement/affEvenement/77",
    calendar_url: "https://calendar.google.com/calendar/ical/t8352hs3ft8e2ngob31rpijlts%40group.calendar.google.com/public/basic.ics",
    typical_weekday: "Thursday", typical_time: "11:00", typical_location: "Jussieu, salle 15-25-502", location_id: "jussieu",
    recurrence: "Weekly, Thursdays 11:00 (as stated on the seminar page)", published_in_advance: "yes", has_archive: true, kind: "seminar",
    level: "research", topics: ["geometry", "topology", "dynamical-systems"],
    description: "« Ce séminaire s'adresse aux géomètres, topologues et dynamiciens au sens large. […] Les exposés seront accessibles à une audience large, doctorants inclus. »",
    statement_source: "https://www.imj-prg.fr/gestion/evenement/affEvenement/77" },
  { id: "imj-43", name: "Séminaire de Topologie", institution_id: "imj-prg", department: "Topologie et Géométrie Algébriques", source_id: "imj-gestion",
    organizers: "Najib Idrissi, Emmanuel Wagner", official_url: "https://www.imj-prg.fr/gestion/evenement/affEvenement/43",
    mailing_list: "https://listes.services.cnrs.fr/wws/info/sem-top.paris", typical_weekday: "Tuesday", typical_time: "10:45–11:45",
    typical_location: "Sophie Germain", location_id: "sophie-germain",
    recurrence: "Tuesdays 10:45–11:45 at Sophie Germain (as stated in the sem-top.paris mailing-list description)", has_archive: true,
    kind: "seminar", level: "research", topics: ["topology", "algebraic-topology", "low-dim-topology"],
    statement_source: "https://listes.services.cnrs.fr/wws/info/sem-top.paris" },
  { id: "imj-24", name: "Groupe de travail Algèbre et Topologie Homotopiques", institution_id: "imj-prg", source_id: "imj-gestion",
    official_url: "https://www.imj-prg.fr/gestion/evenement/affEvenement/24", kind: "working_group", level: "research",
    topics: ["homotopy-theory", "homological-algebra", "higher-algebra"] },
  { id: "imj-11", name: "Groupe de travail Groupes et géométrie", institution_id: "imj-prg", source_id: "imj-gestion",
    official_url: "https://www.imj-prg.fr/gestion/evenement/affEvenement/11", kind: "working_group", level: "research",
    topics: ["geometric-group-theory", "geometry"] },
  { id: "irif-cat", name: "Catégories supérieures, polygraphes et homotopie", institution_id: "irif", source_id: "irif-cat",
    department: "Pôle Preuves, programmes et systèmes", organizers: "Sylvain Douteau, François Métayer",
    official_url: "https://www.irif.fr/seminaires/cat/index", calendar_url: "https://www.irif.fr/_media/ical/cat.ics", typical_weekday: "Friday",
    typical_time: "14:00", typical_location: "Salle 1013", location_id: "sophie-germain",
    recurrence: "Fridays 14:00, salle 1013 (as stated on the page: « Le vendredi à 14h, salle 1013 »)", has_archive: true, kind: "working_group",
    level: "research", topics: ["higher-categories", "homotopy-theory", "category-theory"], statement_source: "https://www.irif.fr/seminaires/cat/index" },
  { id: "irif-hott", name: "La théorie des types et la théorie de l'homotopie", institution_id: "irif", source_id: "irif-hott", organizers: "Sylvain Douteau",
    official_url: "https://www.irif.fr/seminaires/hott/index", calendar_url: "https://www.irif.fr/_media/ical/hott.ics", typical_weekday: "Friday",
    typical_time: "14:00", typical_location: "Salle 1013", location_id: "sophie-germain",
    recurrence: "Fridays 14:00, salle 1013 (as stated on the page; last listed sessions in 2024)", has_archive: true, kind: "working_group",
    level: "research", topics: ["homotopy-theory", "logic", "category-theory"], statement_source: "https://www.irif.fr/seminaires/hott/index" },
  { id: "irif-topos", name: "Topos pour la réalisabilité", institution_id: "irif", source_id: "irif-topos", organizers: "Dominik Kirst, Umberto Tarantino",
    official_url: "https://www.irif.fr/seminaires/topos/index", calendar_url: "https://www.irif.fr/_media/ical/topos.ics", typical_weekday: "Friday",
    typical_time: "15:00", typical_location: "Salle 3063", location_id: "sophie-germain", recurrence: "Fridays 15:00, salle 3063 (as stated on the page)",
    has_archive: true, kind: "working_group", level: "research", topics: ["category-theory", "logic"],
    description: "Reading group on realizability toposes.", statement_source: "https://www.irif.fr/seminaires/topos/index" },
  { id: "cmls-geometrie", name: "Séminaire de géométrie (CMLS)", institution_id: "cmls", source_id: "cmls-geometrie", department: "Équipe Géométrie et Dynamique",
    organizers: "Lorenzo Fantini, Gerard Freixas", official_url: "https://cmls.ip-paris.fr/recherche/geometrie-et-dynamique/seminaire-de-geometrie",
    location_id: "polytechnique", has_archive: true, kind: "seminar", level: "research", topics: ["geometry", "algebraic-geometry"] },
  { id: "agm-gsd", name: "Séminaire géométrie et systèmes dynamiques (AGM, Cergy)", institution_id: "agm", source_id: "agm-seminaires",
    official_url: "https://cyagm.cyu.fr/seminaire-geometrie-et-systemes-dynamiques-1", location_id: "cergy", has_archive: true, kind: "seminar",
    level: "research", topics: ["geometry", "dynamical-systems"], description: "Official page lists sessions up to 2024 only (checked Sept. 2026)." },
  { id: "agm-edp", name: "Séminaire Analyse et EDP (AGM, Cergy)", institution_id: "agm", source_id: "agm-seminaires",
    official_url: "https://cyagm.cyu.fr/seminaires-agm", location_id: "cergy", has_archive: true, kind: "seminar", level: "research",
    topics: ["analysis", "pde"], description: "Official page lists sessions up to 2024 only (checked Sept. 2026)." },
  { id: "paris-apres-midi-topologie", name: "Après-midi de topologie (Paris)", institution_id: "laga", department: "Topologie Algébrique (LAGA) and partners",
    source_id: "laga-sta", official_url: "https://www.math.univ-paris13.fr/accueil/equipes/ta/seminaire-de-lequipe-ta/", kind: "conference",
    level: "research", topics: ["algebraic-topology", "homotopy-theory", "topology"], has_archive: true,
    description: "Afternoons of several topology talks announced in the LAGA topology seminar listing, e.g. « Après-midi parisienne de topologie » (8 Jan 2026, LAGA) and « Après-midi topologie algébrique » (26 Mar 2026, Sophie Germain). Dates are irregular: no recurrence is claimed. Announcements also circulate on the sem-top.paris mailing list." },
  ...IRIF_SEMINARS.filter(([code]) => !["cat", "hott", "topos"].includes(code)).map(([code, name, topics, kind]): RawSeries => ({
    id: `irif-${code}`, name, institution_id: "irif", source_id: `irif-${code}`, official_url: `https://www.irif.fr/seminaires/${code}/index`,
    calendar_url: `https://www.irif.fr/_media/ical/${code}.ics`, location_id: "sophie-germain", kind, level: "research", topics, has_archive: true,
  })),
  ...LAGA_SEMINARS.map(([code, name, team, org, page, topics]): RawSeries => ({
    id: `laga-${code}`, name, institution_id: "laga", department: team, source_id: `laga-${code}`, organizers: org, official_url: page,
    location_id: "villetaneuse", has_archive: true, kind: "seminar", level: "research", topics,
  })),
];

// IMJ-PRG team codes shown in the event system → topics.
export const IMJ_TEAMS: Record<string, [string, string[]]> = {
  tga: ["Topologie et Géométrie Algébriques", []], // spans topology AND algebraic geometry: rely on series names
  gr: ["Groupes, Représentations et Géométrie", ["representation-theory", "group-theory"]],
  fa: ["Formes Automorphes", ["number-theory", "representation-theory"]],
  tn: ["Théorie des Nombres", ["number-theory"]],
  aa: ["Analyse Algébrique", ["algebraic-geometry", "geometry"]],
  acg: ["Analyse Complexe et Géométrie", ["geometry"]],
  gd: ["Géométrie et Dynamique", ["geometry", "dynamical-systems"]],
  lm: ["Logique Mathématique", ["logic"]],
  af: ["Analyse Fonctionnelle", ["analysis"]],
  ao: ["Algèbres d'Opérateurs", ["operator-algebras"]],
  co: ["Combinatoire et Optimisation", ["combinatorics"]],
  hsm: ["Histoire des Sciences Mathématiques", ["history"]],
  doctorants: ["Doctorants", []],
};

export const FEEDS: [string, string, string, string][] = [
  ["quanta-math", "Quanta Magazine — Mathematics", "https://www.quantamagazine.org/mathematics/feed/", "news"],
  ["ihes-news", "IHES — Actualités", "https://www.ihes.fr/feed/", "institute"],
  ["abel-prize", "The Abel Prize", "https://abelprize.no/rss.xml", "prize"],
  ["cnrs-maths", "CNRS Mathématiques (INSMI)", "https://www.insmi.cnrs.fr/fr/rss.xml", "institute"],
];
